[tool.poetry]
name = "advent-ai"
version = "0.1.0"
description = "Chatbot helper for Advent of Code"
authors = ["Cam Crow <19ccrow99@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
